default:
	javac -d ./ linkUpdate.java linkCost.java dvSend.java resendProbe.java timer.java probeThread.java ackThread.java dvThread.java
	javac cnnode.java
all: default

clean:
	rm -rf *.class
	rm -rf pack4
